# Numpy Exercise

#### 1. Import the numpy package under the name as np  

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration

In [2]:
print(np.__version__)
print(np.show_config())

1.26.4
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /usr/local/include
    lib directory: /usr/local/lib
    name: openblas64
    openblas configuration: USE_64BITINT=1 DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK= NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP= HASWELL MAX_THREADS=2
    pc file directory: /usr/local/lib/pkgconfig
    version: 0.3.23.dev
  lapack:
    detection method: internal
    found: true
    include directory: unknown
    lib directory: unknown
    name: dep139863411681952
    openblas configuration: unknown
    pc file directory: unknown
    version: 1.26.4
Compilers:
  c:
    args: -fno-strict-aliasing
    commands: cc
    linker: ld.bfd
    linker args: -Wl,--strip-debug, -fno-strict-aliasing
    name: gcc
    version: 10.2.1
  c++:
    commands: c++
    linker: ld.bfd
    linker args: -Wl,--strip-debug
    name: gcc
    version: 10.2.1
  cython:
    commands: cython
    linker: cython
    name: cython
   

#### 3. Create a null vector of size 10

In [3]:
a=np.zeros(10)
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4.  How to find the memory size of any array

In [4]:
print(a.size)

10


#### 5.  How to get the documentation of the numpy add function from the command line?

In [5]:
np.add?

#### 6.  Create a null vector of size 10 but the fifth value which is 1

In [6]:
b=np.zeros(10)
b[4]=1
print(b)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7.  Create a vector with values ranging from 10 to 49

In [7]:
c=np.arange(10,50, dtype=int)
print(c)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8.  Reverse a vector (first element becomes last)

In [8]:
d=np.array([1,4,6,7,9])
print(d[::-1])

[9 7 6 4 1]


#### 9.  Create a 3x3 matrix with values ranging from 0 to 8

In [9]:
e=np.arange(0,9).reshape(3,3)
print(e)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\]

In [10]:
z=np.array([1,2,0,0,4,0])
print(np.nonzero(z))

(array([0, 1, 4]),)


#### 11. Create a 3x3 identity matrix

In [11]:
f=np.eye(3)
print(f)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values

In [12]:
g=np.random.random((3,3,3))
print(g)

[[[0.58362504 0.96545311 0.25011641]
  [0.16248256 0.29515755 0.77644654]
  [0.54370601 0.78180212 0.18881417]]

 [[0.11846793 0.29183123 0.33797073]
  [0.74952083 0.40951555 0.53538358]
  [0.52955857 0.77597059 0.10520964]]

 [[0.23600475 0.76665172 0.01400422]
  [0.1469389  0.57880673 0.89922365]
  [0.66342461 0.9114335  0.78847014]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values

In [13]:
h=np.random.random((10,10))
print(np.min(h))
print(np.max(h))

0.0008688302134032266
0.9999650747508958


#### 14. Create a random vector of size 30 and find the mean value

In [14]:
i=np.arange(30)
print(np.mean(i))

14.5


#### 15. Create a 2d array with 1 on the border and 0 inside

In [15]:
array_1=np.ones((5,5))
array_1[1:-1,1:-1]=0
print(array_1)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array?

In [16]:
c1=np.ones((5,5))
c1=np.pad(c1,pad_width=1,mode="constant",constant_values=0)
print(c1)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression?

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [17]:
mat1=np.diag(1+np.arange(4),k=-1)
print(mat1)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern

In [18]:
check=np.zeros((8,8),dtype=int)
check[1::2,::2]=1
check[::2,1::2]=1
print(check)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [19]:
array2=np.unravel_index(99,(6,7,8))