# Numpy Exercise

#### 1. Import the numpy package under the name  (★☆☆)

In [ ]:
import numpy as np

#### 2. Print the numpy version and the configuration  (★☆☆)

In [ ]:
print(np.__version__)
print(np.show_config())

1.26.4
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /usr/local/include
    lib directory: /usr/local/lib
    name: openblas64
    openblas configuration: USE_64BITINT=1 DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK= NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP= HASWELL MAX_THREADS=2
    pc file directory: /usr/local/lib/pkgconfig
    version: 0.3.23.dev
  lapack:
    detection method: internal
    found: true
    include directory: unknown
    lib directory: unknown
    name: dep139863411681952
    openblas configuration: unknown
    pc file directory: unknown
    version: 1.26.4
Compilers:
  c:
    args: -fno-strict-aliasing
    commands: cc
    linker: ld.bfd
    linker args: -Wl,--strip-debug, -fno-strict-aliasing
    name: gcc
    version: 10.2.1
  c++:
    commands: c++
    linker: ld.bfd
    linker args: -Wl,--strip-debug
    name: gcc
    version: 10.2.1
  cython:
    commands: cython
    linker: cython
    name: cython
   

#### 3. Create a null vector of size 10 (★☆☆)

In [ ]:
x=np.zeros(10)
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4.  How to find the memory size of any array (★☆☆)

In [ ]:
print(np.size(x))

10


#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆)

In [ ]:
np.add?


#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [ ]:
y=np.zeros(10)
y[4]=1
print(y)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆)

In [ ]:
range_array=np.arange(10,50)
print(range_array)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8.  Reverse a vector (first element becomes last) (★☆☆)

In [ ]:
reverse_array=np.flip(range_array)
print(reverse_array)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [ ]:
mat=np.arange(0,9).reshape(3,3)
print(mat)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆)

In [ ]:
a=np.array([1,2,0,0,4,0])
print(np.nonzero(a))

(array([0, 1, 4]),)


#### 11. Create a 3x3 identity matrix (★☆☆)

In [ ]:
I=np.eye(3)
print(I)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [ ]:
import random
random_array=np.random.random((3,3,3))
print(random_array)

[[[0.23413971 0.60239317 0.15063501]
  [0.31502333 0.11333    0.13468802]
  [0.97089947 0.28399587 0.81612232]]

 [[0.18436487 0.01491304 0.24637166]
  [0.02992901 0.6664818  0.87667508]
  [0.82441455 0.34123069 0.41156406]]

 [[0.60495495 0.9338189  0.65220186]
  [0.01305932 0.20718073 0.29077586]
  [0.08654377 0.92606391 0.08627837]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [ ]:
b=np.random.random((10,10))
print("The min value of array is : " ,np.min(b))
print("The max value of array is : " , np.max(b))

The min value of array is :  0.006897500528821321
The max value of array is :  0.9945283339617238


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [ ]:
c=np.random.random(30)
print(np.mean(c))

0.5771587152110946


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [ ]:
array_1=np.ones((5,5))
array_1[1:-1,1:-1]=0
print(array_1)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [ ]:
c1=np.ones((5,5))
c1=np.pad(c1,pad_width=1,mode='constant',constant_values=0)
print(c1)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [ ]:
print(0*np.nan)
print(np.nan==np.nan)
print(np.inf>np.nan)
print(np.nan-np.nan)
print(np.nan in set([np.nan]))
print(0.3==3*0.1)

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [ ]:
mat1=np.diag(1+np.arange(4),k=-1)
print(mat1)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [ ]:
check=np.zeros((8,8),dtype=int)
check[1::2,::2]=1
check[::2,1::2]=1
print(check)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [ ]:
array2=np.unravel_index(99,(6,7,8))
print(array2)

(1, 5, 3)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [ ]:
check1=np.array([[0,1],[1,0]])
check2=np.tile(check1,(4,4))
print(check2)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [ ]:
mat3=np.random.random((5,5))
mat3=(mat3-np.mean(mat3))/np.std(mat3)
print(mat3)

[[-1.24414394e+00 -1.56073036e+00  8.81532269e-01 -5.70739993e-01
   4.41137332e-01]
 [ 1.32971288e+00 -7.93375879e-01  9.77747138e-01  1.40747657e+00
   9.87506031e-01]
 [-1.27542499e+00  1.33587749e+00  1.33046569e+00  1.33928475e+00
  -7.02217537e-01]
 [ 2.38115910e-01 -8.91154088e-01 -2.78016349e-01 -1.61063359e+00
  -6.91381385e-01]
 [ 8.12508300e-01  4.29030086e-04 -2.92293148e-01 -1.09008337e+00
  -8.15987664e-02]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [ ]:
a=np.dtype([("r",np.ubyte,1),("g",np.ubyte,1),("b",np.ubyte,1),("a",np.ubyte,1)])
print(a)

[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')]


<ipython-input-32-fcf70a765177>:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  a=np.dtype([("r",np.ubyte,1),("g",np.ubyte,1),("b",np.ubyte,1),("a",np.ubyte,1)])


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [ ]:
mat_a=np.random.random((5,3))
mat_b=np.random.random((3,2))
mat_c=np.dot(mat_a,mat_b)
print(mat_c)

[[1.75627546 0.95098437]
 [0.99802813 0.09719994]
 [0.23170418 0.34189838]
 [0.64714558 0.49074118]
 [1.37090007 0.48671264]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [ ]:
myarray=np.arange(11)
myarray[(myarray>=3)&(myarray<=8)]*=-1
print(myarray)

[ 0  1  2 -3 -4 -5 -6 -7 -8  9 10]


#### 26. What is the output of the following script? (★☆☆)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

print(sum(range(5),-1)) = 9
Importing it by * means it will load all functions of numpy in local namespace
You can directly use array([1,2,3]) instead of np .array


In [ ]:
print(sum(range(5),-1))

9


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

All expression except the last one will work


In [ ]:
z=np.array([1,2,3,4])
print(z**z)
print(2<<z>>2)
print(z<-z)
print(1j*z)
print(z/1/1)


[  1   4  27 256]
[1 2 4 8]
[False False False False]
[0.+1.j 0.+2.j 0.+3.j 0.+4.j]
[1. 2. 3. 4.]


#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

for first statement it will give NaN value
for second statement it will give 0 but an warning of division by zero too
for third statement ,it gives a lowest number possible with a warning of invalid casting

In [ ]:
print(np.array([np.nan]).astype(int).astype(float))

[-9.22337204e+18]


<ipython-input-37-8ac629ca88a6>:1: RuntimeWarning: invalid value encountered in cast
  print(np.array([np.nan]).astype(int).astype(float))


#### 29. How to round away from zero a float array ? (★☆☆)

In [ ]:
mat4=np.random.uniform(-10,10,10)
print(np.copysign(np.ceil(np.abs(mat4)),mat4))

[ 9.  5.  2.  6.  2. -3. -7.  9. -7. -4.]


#### 30. How to find common values between two arrays? (★☆☆)

In [ ]:
A=np.array([1,2,3,4])
B=np.array([2,3,7,10])
print(np.intersect1d(A,B))

[2 3]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [ ]:
np.seterr(all="ignore")


{'divide': 'warn', 'over': 'warn', 'under': 'ignore', 'invalid': 'warn'}

#### 32. Is the following expressions true? (★☆☆)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

No they are not the same expression as np.sqrt of -1 will not work and give you nan while the np.emath.sqrt can print the imaginary root of -1 in complex form

In [ ]:
print(np.sqrt(-1))
print(np.emath.sqrt(-1))

nan
1j


#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [ ]:
from datetime import date,timedelta
today=date.today()
print("Today's date: ", today)
yesterday=today-timedelta(days=1)
print("Yesterday: ", yesterday)
tomorrow=today+timedelta(days=1)
print("Tomorrow : ", tomorrow)

Today's date:  2024-08-14
Yesterday:  2024-08-13
Tomorrow :  2024-08-15


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [ ]:
print(np.arange('2016-07','2016-08',dtype='datetime64[D]'))

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆)

In [ ]:
A=np.ones(3)
B=np.ones(3)*3
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([-2., -2., -2.])

#### 36. Extract the integer part of a random array using 5 different methods (★★☆)

In [ ]:
A=np.random.uniform(0,10,10)
print("Float Array: ", A)
#Integer extraction
print(A//1)
print(np.floor(A))
print(np.trunc(A))
print(A.astype(int))
print(A-A%1)

Float Array:  [9.0464584  9.62450919 4.60968992 0.70531442 7.19431755 3.3985197
 9.7905724  5.08497473 8.16066347 3.99741421]
[9. 9. 4. 0. 7. 3. 9. 5. 8. 3.]
[9. 9. 4. 0. 7. 3. 9. 5. 8. 3.]
[9. 9. 4. 0. 7. 3. 9. 5. 8. 3.]
[9 9 4 0 7 3 9 5 8 3]
[9. 9. 4. 0. 7. 3. 9. 5. 8. 3.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [ ]:
mat5=np.arange(0,5)
mat5=np.tile(mat5,(5,1))
print(mat5)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [ ]:
C=np.random.randint(10,size=10)
print(C)

[2 3 7 4 4 9 0 7 8 6]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [ ]:
D=np.linspace(0,1,11,endpoint=False)[1:]
print(D)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [ ]:
E=np.random.randint(10,size=10)
print("Random vector: ", E)
E.sort()
print("Sorted Array :\n" ,E)

Random vector:  [5 1 7 0 3 5 4 8 4 1]
Sorted Array :
 [0 1 1 3 4 4 5 5 7 8]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [ ]:
x=np.arange(10)
np.add.reduce(x)

45

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [ ]:
A=np.random.randint(5,size=5)
B=np.random.randint(5,size=5)
print(np.array_equal(A,B))

False


#### 43. Make an array immutable (read-only) (★★☆)

In [ ]:
my_array=np.eye(3)
my_array.flags.writeable=False
#my_array[0,1]=1 # This will raise an error that assignment destination is read only

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [ ]:
mat6=np.random.random((10,2))
x,y=mat6[:,0],mat6[:,1]
r=np.sqrt(x**2+y**2)
t=np.arctan(y/x)
print("Modulo array: " , r)
print("Angle array: ", t)

Modulo array:  [0.75311982 0.55246676 1.1148032  1.00344191 0.3683927  0.42897937
 1.13162019 0.84923006 0.37288746 0.79306651]
Angle array:  [1.5468604  0.22351459 0.5109116  1.04545658 0.27205775 0.69422525
 0.48725164 1.50253417 0.9105206  1.12260614]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [ ]:
v=np.random.randint(20,size=10)
print("Original Array :", v)
v[v.argmax()]=0
print("Modified Array :", v)

Original Array : [ 4  7  9  4 16 19  5 17 15 11]
Modified Array : [ 4  7  9  4 16  0  5 17 15 11]


#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆)

In [ ]:
x=np.linspace(0,1,5)
y=np.linspace(0,1,5)
X,Y=np.meshgrid(x,y)
print(X)
print(Y)

[[0.   0.25 0.5  0.75 1.  ]
 [0.   0.25 0.5  0.75 1.  ]
 [0.   0.25 0.5  0.75 1.  ]
 [0.   0.25 0.5  0.75 1.  ]
 [0.   0.25 0.5  0.75 1.  ]]
[[0.   0.   0.   0.   0.  ]
 [0.25 0.25 0.25 0.25 0.25]
 [0.5  0.5  0.5  0.5  0.5 ]
 [0.75 0.75 0.75 0.75 0.75]
 [1.   1.   1.   1.   1.  ]]


####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

In [ ]:
X=np.arange(8)
Y=X+0.5
C=1.0/np.subtract.outer(X,Y)
print(C)

[[-2.         -0.66666667 -0.4        -0.28571429 -0.22222222 -0.18181818
  -0.15384615 -0.13333333]
 [ 2.         -2.         -0.66666667 -0.4        -0.28571429 -0.22222222
  -0.18181818 -0.15384615]
 [ 0.66666667  2.         -2.         -0.66666667 -0.4        -0.28571429
  -0.22222222 -0.18181818]
 [ 0.4         0.66666667  2.         -2.         -0.66666667 -0.4
  -0.28571429 -0.22222222]
 [ 0.28571429  0.4         0.66666667  2.         -2.         -0.66666667
  -0.4        -0.28571429]
 [ 0.22222222  0.28571429  0.4         0.66666667  2.         -2.
  -0.66666667 -0.4       ]
 [ 0.18181818  0.22222222  0.28571429  0.4         0.66666667  2.
  -2.         -0.66666667]
 [ 0.15384615  0.18181818  0.22222222  0.28571429  0.4         0.66666667
   2.         -2.        ]]


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [ ]:
for dtype in [np.float32,np.float64]:
  print(np.finfo(dtype).min)
  print(np.finfo(dtype).max)
for dtype in [np.int8,np.int32,np.int64]:
  print(np.iinfo(dtype).min)
  print(np.iinfo(dtype).max)


-3.4028235e+38
3.4028235e+38
-1.7976931348623157e+308
1.7976931348623157e+308
-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807


#### 49. How to print all the values of an array? (★★☆)

In [ ]:
np.set_printoptions()
a=np.zeros((5,5))
print(a)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [ ]:
x = np.arange(10)
a = np.random.uniform(0, 10)

# Displaying the value used for comparison
print("Value to compare:")
print(a)

# Finding the index of the element in array 'x' closest to the generated value 'a'
index = (np.abs(x - a)).argmin()
print(x[index])

Value to compare:
2.226460235948704
2


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [ ]:
poscolor=np.zeros(10,[('position',[('x',float,1),('y',float,1)]),('color',[('r',float,1),('g',float,1),('b',float,1)])])
print(poscolor)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


<ipython-input-75-676c76bff536>:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  poscolor=np.zeros(10,[('position',[('x',float,1),('y',float,1)]),('color',[('r',float,1),('g',float,1),('b',float,1)])])


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [ ]:
y=np.random.random((100,2))
X,Y=np.atleast_2d(y[:,0],y[:,1])
dist=np.sqrt((X-X.T)**2+(Y-Y.T)**2)
print(dist)

[[0.         0.56720526 0.95746097 ... 0.2590942  0.81402736 0.88915423]
 [0.56720526 0.         0.39542762 ... 0.46676691 0.32675836 0.33601798]
 [0.95746097 0.39542762 0.         ... 0.81329306 0.24817599 0.0819399 ]
 ...
 [0.2590942  0.46676691 0.81329306 ... 0.         0.62434136 0.73586578]
 [0.81402736 0.32675836 0.24817599 ... 0.62434136 0.         0.17103946]
 [0.88915423 0.33601798 0.0819399  ... 0.73586578 0.17103946 0.        ]]


#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [ ]:
c=np.arange(10,dtype=np.float32)
c=c.astype(np.int32,copy=False)
print(c.dtype)

int32


#### 54. How to read the following file? (★★☆)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [ ]:
from io import StringIO
s = StringIO("""1, 2, 3, 4, 5\n
                6,  ,  , 7, 8\n
                 ,  , 9,10,11\n""")
N = np.genfromtxt(s, delimiter=",", dtype=np.int32)
print(N)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [ ]:
S=np.arange(6).reshape(3,2)
for index,value in np.ndenumerate(S):
  print(index , value)
for index in np.ndindex(S.shape):
  print(index)

(0, 0) 0
(0, 1) 1
(1, 0) 2
(1, 1) 3
(2, 0) 4
(2, 1) 5
(0, 0)
(0, 1)
(1, 0)
(1, 1)
(2, 0)
(2, 1)


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [ ]:
X,Y=np.meshgrid(np.linspace(-2,2,10),np.linspace(-2,2,10))
D=np.sqrt(X*X+Y*Y)
sigma,mu=1.0,0.0
G=np.exp(-((D-mu)**2)/(2.0*sigma**2))
print(G)

[[0.01831564 0.0403616  0.07300087 0.10836802 0.13203459 0.13203459
  0.10836802 0.07300087 0.0403616  0.01831564]
 [0.0403616  0.08894358 0.16086971 0.2388072  0.29096046 0.29096046
  0.2388072  0.16086971 0.08894358 0.0403616 ]
 [0.07300087 0.16086971 0.29096046 0.43192377 0.52625189 0.52625189
  0.43192377 0.29096046 0.16086971 0.07300087]
 [0.10836802 0.2388072  0.43192377 0.64118039 0.7812082  0.7812082
  0.64118039 0.43192377 0.2388072  0.10836802]
 [0.13203459 0.29096046 0.52625189 0.7812082  0.95181678 0.95181678
  0.7812082  0.52625189 0.29096046 0.13203459]
 [0.13203459 0.29096046 0.52625189 0.7812082  0.95181678 0.95181678
  0.7812082  0.52625189 0.29096046 0.13203459]
 [0.10836802 0.2388072  0.43192377 0.64118039 0.7812082  0.7812082
  0.64118039 0.43192377 0.2388072  0.10836802]
 [0.07300087 0.16086971 0.29096046 0.43192377 0.52625189 0.52625189
  0.43192377 0.29096046 0.16086971 0.07300087]
 [0.0403616  0.08894358 0.16086971 0.2388072  0.29096046 0.29096046
  0.2388072  0

#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [ ]:
n=9
p=4
D=np.zeros((n,n))
np.put(D,np.random.choice(range(n*n),p,replace=False),1)
print(D)

[[0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆)

In [ ]:
X=np.random.rand(5,10)
Y=X-X.mean(axis=1,keepdims=True)
print(Y)

[[ 0.21052093 -0.1934467  -0.03657898 -0.24757765 -0.3523311   0.42424171
   0.36261652 -0.21051657  0.08136239 -0.03829054]
 [-0.37736027  0.20350264  0.52194589 -0.30232753 -0.34927835  0.19654788
   0.28015641  0.51702248 -0.37205643 -0.31815272]
 [-0.52984823  0.21109025  0.26815678 -0.57597915 -0.14564595  0.2238758
   0.39299892 -0.05580604  0.26498933 -0.05383172]
 [-0.05597421  0.15972835  0.25436506 -0.31523137 -0.01587138 -0.02898537
   0.33354349  0.2192474   0.07043682 -0.62125878]
 [-0.31511759  0.21183196  0.3285641   0.33200583 -0.39916937 -0.37025015
  -0.35792847  0.33567333 -0.17875775  0.41314811]]


#### 59. How to sort an array by the nth column? (★★☆)

In [ ]:
N=np.random.randint(0,10,(3,3))
print(N)
print(N[N[:,0].argsort()])

[[5 3 9]
 [4 4 3]
 [0 5 3]]
[[0 5 3]
 [4 4 3]
 [5 3 9]]


#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [ ]:
arr1 = np.random.randint(0,3,(3,10))
print((~arr1.any(axis=0)).any())

True


#### 61. Find the nearest value from a given value in an array (★★☆)

In [ ]:
arr2=np.random.uniform(0,2,10)
x=0.5
m=arr2.flat[np.abs(arr2-x).argmin()]
print(m)

0.5303661293686084


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [ ]:
A=np.arange(3).reshape(1,3)
B=np.arange(3).reshape(3,1)
it=np.nditer([A,B,None])
for x,y,z in it:
  z[...]=x+y
print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆)

In [ ]:
class ArrayName(np.ndarray):
  def __new__(cls,array,name="no name"):
    obj=np.asarray(array).view(cls)
    obj.name=name
    return obj
  def __array_finalize__(self,obj):
    if obj is None:return
    self.info=getattr(obj,'name','no name')

A=ArrayName(np.arange(10),'Diksha')
print(A.name)


Diksha


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [ ]:
A=np.ones(10)
B=np.random.randint(0,len(A),20)
np.add.at(A,B,1)
print(A)

[4. 1. 3. 4. 3. 3. 2. 4. 3. 3.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [ ]:
X=[2,8,9,0,2,6,7,0]
Y=[3,4,1,9,6,5,4,3]
I=np.bincount(X,Y)
print(I)

[12.  0.  9.  0.  0.  0.  5.  4.  4.  1.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★)

In [ ]:
w,h=4,4
I=np.random.randint(0,2,(h,w,3)).astype(np.ubyte)
F=I[...,0]*256*256+I[...,1]*256+I[...,2]
n=len(np.unique(F))
print(n)

4


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [ ]:
A=np.random.randint(0,10,(3,4,3,4))
sum = A.reshape(A.shape[:-2] + (-1,)).sum(axis=-1)
print(sum)


[[72 69 62 65]
 [48 49 66 72]
 [60 62 46 45]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

In [ ]:

D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)

# Pandas solution as a reference due to more intuitive code
import pandas as pd
print(pd.Series(D).groupby(S).mean())

[0.71436761 0.27971573 0.5693769  0.41378303 0.29652434 0.45402277
 0.75108818 0.49742956 0.43391348 0.55624292]
0    0.714368
1    0.279716
2    0.569377
3    0.413783
4    0.296524
5    0.454023
6    0.751088
7    0.497430
8    0.433913
9    0.556243
dtype: float64


#### 69. How to get the diagonal of a dot product? (★★★)

In [ ]:
A=np.random.uniform(0,10,(5,5))
B=np.random.uniform(0,10,(5,5))
np.diag(np.dot(A,B))

array([ 60.34528651, 183.18823045,  67.09852283, 205.64080333,
        85.6719658 ])

#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [ ]:
Z=np.array([1,2,3,4,5])
Z0=np.zeros(len(Z)+3*len(Z-1))
Z0[::4]=Z
print(Z0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5. 0. 0. 0.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

In [ ]:
A=np.ones((5,5,3))
B=2*np.ones((5,5))
print(A*B[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


#### 72. How to swap two rows of an array? (★★★)

In [ ]:
A=np.arange(16).reshape(4,4)
A[[0,1]]=A[[1,0]]
print(A)

[[ 4  5  6  7]
 [ 0  1  2  3]
 [ 8  9 10 11]
 [12 13 14 15]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

In [ ]:
faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)

[( 0, 73) ( 0, 90) ( 5, 64) ( 5, 97) ( 6, 27) ( 6, 52) ( 6, 66) ( 6, 76)
 (11, 42) (11, 46) (12, 66) (12, 95) (14, 48) (14, 67) (18, 39) (18, 99)
 (27, 66) (28, 57) (28, 67) (39, 99) (42, 46) (48, 67) (52, 76) (57, 67)
 (63, 64) (63, 95) (64, 95) (64, 97) (66, 95) (73, 90)]


#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

In [ ]:
C=np.bincount([2,1,9,7,4,6])
A=np.repeat(np.arange(len(C)),C)
print(A)

[1 2 4 6 7 9]


#### 75. How to compute averages using a sliding window over an array? (★★★)

In [ ]:
def sliding_window(arr,n):
  ret = np.cumsum(arr, dtype=float)
  ret[n:] = ret[n:] - ret[:-n]
  return ret[n - 1:] / n
A=np.arange(20)
print(sliding_window(A,3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★)

In [ ]:
from numpy.lib import stride_tricks

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.itemsize, a.itemsize)
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = rolling(np.arange(10), 3)
print(Z)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

In [ ]:
Z = np.random.randint(0,2,100)
np.logical_not(Z, out=Z)

Z = np.random.uniform(-1.0,1.0,100)
np.negative(Z, out=Z)

array([-0.63445517,  0.23764792, -0.45963434,  0.39267477, -0.90352134,
       -0.30512068, -0.0637841 , -0.58918558, -0.73266504, -0.16795436,
       -0.72361942,  0.17034039, -0.9261892 ,  0.85581595, -0.41494256,
       -0.01283907, -0.15153134,  0.01772037,  0.9442893 ,  0.56858676,
       -0.9533209 , -0.88366747, -0.51523057, -0.44735594,  0.7304002 ,
       -0.41953746,  0.52282616,  0.98147173,  0.39217514, -0.15549531,
       -0.2993903 , -0.01587879, -0.71101867, -0.9025181 , -0.13843648,
       -0.39615737, -0.71067088,  0.32055932,  0.81051241, -0.28636287,
        0.44802942,  0.88389215,  0.64550975, -0.81702284, -0.08155094,
       -0.85695364, -0.93742634, -0.11626232, -0.7098202 , -0.62691161,
       -0.79231452,  0.90612005, -0.66505699,  0.25156006, -0.29196744,
        0.86251899, -0.52702567,  0.69607377, -0.59615446, -0.9136153 ,
       -0.86703154,  0.66281248,  0.5840259 ,  0.24516498, -0.64747127,
        0.34411487, -0.69765588, -0.64947211, -0.41868289, -0.07

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

In [ ]:
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))

[1.06565673 6.50965509 5.95414222 7.49142731 3.36022108 1.01429511
 9.36711391 2.55836473 3.10822082 3.61637033]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

In [ ]:
#P0 P1 from prev question and generated a set of p  points in this question
p = np.random.uniform(-10, 10, (10,2))
print(np.array([distance(P0,P1,p_i) for p_i in p]))

[[ 2.02539023  1.34408278  0.72669492  7.62396299  1.1447574   4.22748795
   5.19386159  1.29391334  0.75937261  7.88611234]
 [ 2.1911924   0.35284871  0.55661693  3.00198683  4.510776    1.78704045
   0.6427658   0.38614737  4.0162063   6.81204808]
 [ 5.14227537  1.67670621  0.61085793  0.11128107  7.40896607  0.91559592
   0.59297178  2.86054909  6.89719877  4.55391762]
 [ 1.58982756  7.3835593   8.43892501  2.31761027  1.9129148   6.0186477
   6.31990291  4.92376354  1.20269732 12.84709269]
 [ 1.31444365  4.35114112  5.31677608  3.12560959  2.49089029  4.71503792
   3.15521074  3.1234262   1.87490767 10.7014505 ]
 [ 2.64952059  8.73604454  7.99698529  3.94772716  7.15929186  2.66405533
   8.35227471  6.03371098  6.9020706   0.35562652]
 [ 3.02790522  4.36820572  5.44334648  1.31319867  3.96241279  3.53317284
   4.63189652  2.19244464  3.31338319  9.97698514]
 [ 6.5981214   4.86388342  3.78121956  0.88259022  9.51996291  3.49811869
   1.24591365  5.71222533  9.07408916  1.54787495]
 

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

In [ ]:
def extract_subarray(arr, center, shape, fill_value=0):
    # Get the shape of the input array
    arr_shape = np.array(arr.shape)

    # Calculate the starting and ending indices of the subarray
    start_idx = np.array(center) - np.array(shape) // 2
    end_idx = start_idx + np.array(shape)

    # Initialize the result array filled with the fill_value
    result = np.full(shape, fill_value, dtype=arr.dtype)

    # Calculate the region of the input array to copy to the result array
    src_start = np.maximum(0, start_idx)
    src_end = np.minimum(arr_shape, end_idx)

    # Calculate the region in the result array to fill with values from the input array
    dst_start = np.maximum(0, -start_idx)
    dst_end = dst_start + (src_end - src_start)

    # Copy the relevant part of the input array to the result array
    result[tuple(map(slice, dst_start, dst_end))] = arr[tuple(map(slice, src_start, src_end))]

    return result

# Example usage
arr = np.arange(25).reshape(5, 5)
center = (2, 2)
shape = (3, 3)
subarray = extract_subarray(arr, center, shape, fill_value=0)

print(subarray)


[[ 6  7  8]
 [11 12 13]
 [16 17 18]]


#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★)

In [ ]:
Z=np.arange(1,15,dtype=int)
R=stride_tricks.as_strided(Z,(11,4),(4,4))
print(R)

[[          1  8589934592           2 12884901888]
 [ 8589934592           2 12884901888           3]
 [          2 12884901888           3 17179869184]
 [12884901888           3 17179869184           4]
 [          3 17179869184           4 21474836480]
 [17179869184           4 21474836480           5]
 [          4 21474836480           5 25769803776]
 [21474836480           5 25769803776           6]
 [          5 25769803776           6 30064771072]
 [25769803776           6 30064771072           7]
 [          6 30064771072           7 34359738368]]


#### 82. Compute a matrix rank (★★★)

In [ ]:
Z=np.random.uniform(0,1,(10,10))
U,L,V=np.linalg.svd(Z)
rank=np.sum(L>1e-10)
print(rank)

10


#### 83. How to find the most frequent value in an array?

In [ ]:
Z=np.random.randint(0,12,50)
print(np.bincount(Z).argmax())


2


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

In [ ]:
A=np.random.randint(0,5,(10,10))
n=3
i=1+(A.shape[0]-3)
j=1+(A.shape[1]-3)
C=stride_tricks.as_strided(A,shape=(i,j,n,n),strides=A.strides+A.strides)
print(C)

[[[[1 3 0]
   [0 4 3]
   [0 2 4]]

  [[3 0 0]
   [4 3 2]
   [2 4 3]]

  [[0 0 1]
   [3 2 2]
   [4 3 4]]

  [[0 1 4]
   [2 2 3]
   [3 4 2]]

  [[1 4 3]
   [2 3 0]
   [4 2 3]]

  [[4 3 1]
   [3 0 2]
   [2 3 3]]

  [[3 1 1]
   [0 2 3]
   [3 3 0]]

  [[1 1 2]
   [2 3 0]
   [3 0 1]]]


 [[[0 4 3]
   [0 2 4]
   [1 0 4]]

  [[4 3 2]
   [2 4 3]
   [0 4 3]]

  [[3 2 2]
   [4 3 4]
   [4 3 1]]

  [[2 2 3]
   [3 4 2]
   [3 1 1]]

  [[2 3 0]
   [4 2 3]
   [1 1 2]]

  [[3 0 2]
   [2 3 3]
   [1 2 3]]

  [[0 2 3]
   [3 3 0]
   [2 3 4]]

  [[2 3 0]
   [3 0 1]
   [3 4 0]]]


 [[[0 2 4]
   [1 0 4]
   [4 0 4]]

  [[2 4 3]
   [0 4 3]
   [0 4 3]]

  [[4 3 4]
   [4 3 1]
   [4 3 0]]

  [[3 4 2]
   [3 1 1]
   [3 0 3]]

  [[4 2 3]
   [1 1 2]
   [0 3 0]]

  [[2 3 3]
   [1 2 3]
   [3 0 2]]

  [[3 3 0]
   [2 3 4]
   [0 2 1]]

  [[3 0 1]
   [3 4 0]
   [2 1 2]]]


 [[[1 0 4]
   [4 0 4]
   [3 3 0]]

  [[0 4 3]
   [0 4 3]
   [3 0 1]]

  [[4 3 1]
   [4 3 0]
   [0 1 4]]

  [[3 1 1]
   [3 0 3]
   [1 4 0]]

  [[1 1 2]
   

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★)

In [ ]:
class sym(np.ndarray):
  def __setitem__(self,index,value):
    i,j=index
    super(sym,self).__setitem__((i,j),value)
    super(sym,self).__setitem__((j,i),value)
def symm(Z):
  return np.asarray(Z+Z.T-np.diag(Z.diagonal())).view(sym)
A=symm(np.random.randint(0,5,(5,5)))
A[2,3]=12
print(A)

[[ 1  5  4  3  6]
 [ 5  2  4  6  1]
 [ 4  4  2 12  8]
 [ 3  6 12  4  3]
 [ 6  1  8  3  4]]


#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

In [ ]:
p,n=10,20
C=np.ones((p,n,n))
D=np.ones((p,n,1))
S=np.tensordot(C,D,axes=[[0, 2], [0, 1]])
print(S)

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

In [ ]:

Z = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
                                       np.arange(0, Z.shape[1], k), axis=1)
print(S)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [ ]:

def iterate(Z):
    # Count neighbours
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])

    # Apply rules
    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0,2,(50,50))
for i in range(100): Z = iterate(Z)
print(Z)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


#### 89. How to get the n largest values of an array (★★★)

In [ ]:
Z=np.arange(100)
np.random.shuffle(Z)
n=5
print(Z[np.argsort(Z)[-n:]])
print(Z[np.argpartition(-Z,n)[:n]])

[95 96 97 98 99]
[97 98 99 96 95]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

In [ ]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


#### 91. How to create a record array from a regular array? (★★★)

In [ ]:
#In NumPy, a record array (also known as a structured array) is a way to store heterogeneous data in a single array.
#Unlike regular NumPy arrays, which hold elements of the same data type, record arrays allow you to define different data types for each field (or column) within the array.
Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T,
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(R)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

In [ ]:
x=np.random.rand(int(5e7))
%timeit np.power(x,3)
%timeit x*x*x
%timeit np.einsum('i,i,i->i',x,x,x)

1.53 s ± 210 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
241 ms ± 10.3 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
212 ms ± 17.4 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

In [ ]:
A=np.random.randint(0,5,(8,3))
B=np.random.randint(0,5,(2,2))
C=(A[...,np.newaxis,np.newaxis]==B)
rows=np.where(C.any((3,1)).all(1))[0]
print(rows)

[0 1 2 3 4 5 6 7]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

In [ ]:
Z = np.random.randint(0,5,(10,3))
print(Z)
# solution for arrays of all dtypes (including string arrays and record arrays)
E = np.all(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]
print(U)
print("#########")
U = Z[Z.max(axis=1) != Z.min(axis=1),:]
print(U)

[[2 0 3]
 [4 1 1]
 [1 0 1]
 [2 0 4]
 [2 1 4]
 [0 3 0]
 [3 2 4]
 [2 0 4]
 [1 3 1]
 [1 1 2]]
[[2 0 3]
 [4 1 1]
 [1 0 1]
 [2 0 4]
 [2 1 4]
 [0 3 0]
 [3 2 4]
 [2 0 4]
 [1 3 1]
 [1 1 2]]
#########
[[2 0 3]
 [4 1 1]
 [1 0 1]
 [2 0 4]
 [2 1 4]
 [0 3 0]
 [3 2 4]
 [2 0 4]
 [1 3 1]
 [1 1 2]]


#### 95. Convert a vector of ints into a matrix binary representation (★★★)

In [ ]:
A=np.array([2,4,8,7,16,250],dtype=np.uint8)
print(np.unpackbits(A[:,np.newaxis],axis=1))

[[0 0 0 0 0 0 1 0]
 [0 0 0 0 0 1 0 0]
 [0 0 0 0 1 0 0 0]
 [0 0 0 0 0 1 1 1]
 [0 0 0 1 0 0 0 0]
 [1 1 1 1 1 0 1 0]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

In [ ]:

Z = np.random.randint(0,2,(6,3))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
print(uZ)

# NumPy >= 1.13
uZ = np.unique(Z, axis=0)
print(uZ)

[[0 0 0]
 [0 0 1]
 [0 1 1]
 [1 1 0]]
[[0 0 0]
 [0 0 1]
 [0 1 1]
 [1 1 0]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

In [ ]:
A=np.random.uniform(0,2,10)
B=np.random.uniform(0,2,10)
print(np.einsum('i->',A)) #np.sum(A)
print(np.einsum('i,i->',A,B))#A*B
print(np.einsum('i,i',A,B))#np.inner(A,B)
print(np.einsum('i,j->ij',A,B))#np.outer(A,B)

11.08535191485834
9.163141537233525
9.163141537233525
[[0.24717715 0.26400484 0.75611102 0.60842183 0.64070955 0.39492699
  0.44484859 0.00778598 0.22789033 0.63340954]
 [0.34178564 0.36505423 1.04551689 0.8412988  0.88594483 0.54608758
  0.61511696 0.0107661  0.31511667 0.8758507 ]
 [0.56215864 0.60043011 1.71963443 1.38374273 1.45717516 0.89818828
  1.0117257  0.01770776 0.51829433 1.44057264]
 [0.83521249 0.89207332 2.55490185 2.05585954 2.16495986 1.33445973
  1.50314497 0.02630884 0.77004223 2.1402931 ]
 [0.42515609 0.45410049 1.30054578 1.04651356 1.10204993 0.67929262
  0.76516006 0.01339224 0.39198186 1.08949358]
 [0.7282288  0.77780623 2.22764042 1.79252123 1.88764672 1.16352666
  1.31060475 0.0229389  0.6714063  1.86613956]
 [0.26636224 0.28449605 0.81479791 0.65564556 0.69043935 0.42557995
  0.47937629 0.0083903  0.24557844 0.68257274]
 [0.35017758 0.37401748 1.07118769 0.86195539 0.90769763 0.55949579
  0.63022006 0.01103045 0.32285379 0.89735565]
 [0.23895779 0.25522591 0.

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

In [ ]:
phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)

dr = (np.diff(x)**2 + np.diff(y)**2)**.5 # segment lengths
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)                # integrate path
r_int = np.linspace(0, r.max(), 200) # regular spaced path
x_int = np.interp(r_int, r, x)       # integrate path
y_int = np.interp(r_int, r, y)

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

In [ ]:
X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print(X[M])

[[2. 0. 1. 1.]]


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)

In [ ]:
X = np.random.randn(100) # random 1D array
N = 1000 # number of bootstrap samples
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print(confint)

[-0.08278289  0.27877467]
