# **Starting With Numpy**

In [16]:
import numpy as np
#Creating an array object
arr=np.array([[1,2,3],[4,5,6]])
print("Array is of type: ",type(arr))
print("No. of dimensions: ",arr.ndim)
print("Shape of array: ",arr.shape)
print("Size of array: ",arr.size)
print("Array stores elements of type: ",arr.dtype)

Array is of type:  <class 'numpy.ndarray'>
No. of dimensions:  2
Shape of array:  (2, 3)
Size of array:  6
Array stores elements of type:  int64


# **Creating Array**

In [4]:
a=np.array([[1,2,6],[5,9,10]],dtype='float')
print("Array created from list using float as dtype:\n " ,a)
b=np.array((1,2,8))
print("Array created from tuple :\n ", b)
c=np.zeros((3,4))
print("Array with all zeroes:\n", c)
d=np.full((3,3),6,dtype='complex')
print("Array with all 6s:\n " , d)
e=np.random.random((2,2))
print("Random array : \n", e)
f=np.arange(0,20,3)
print("Sequential array : \n", f )
g=np.linspace(0,4,12)
print("Array with 12 values from 0 to 4 : \n", g)
arr=np.array([[1,2,3,4],
              [6,7,8,5],
              [2,0,7,3]])
newarr=arr.reshape(2,2,3)
print("Original Array: \n",arr)
print("Reshaped array : \n", newarr)
arr=np.array([[3,4,5],[2,9,0]])
flaArr=arr.flatten()
print("Original Array : \n", arr)
print("Flattened Array : \n", flaArr)

Array created from list using float as dtype:
  [[ 1.  2.  6.]
 [ 5.  9. 10.]]
Array created from tuple :
  [1 2 8]
Array with all zeroes:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Array with all 6s:
  [[6.+0.j 6.+0.j 6.+0.j]
 [6.+0.j 6.+0.j 6.+0.j]
 [6.+0.j 6.+0.j 6.+0.j]]
Random array : 
 [[0.7565528  0.7184044 ]
 [0.78354291 0.94958563]]
Sequential array : 
 [ 0  3  6  9 12 15 18]
Array with 12 values from 0 to 4 : 
 [0.         0.36363636 0.72727273 1.09090909 1.45454545 1.81818182
 2.18181818 2.54545455 2.90909091 3.27272727 3.63636364 4.        ]
Original Array: 
 [[1 2 3 4]
 [6 7 8 5]
 [2 0 7 3]]
Reshaped array : 
 [[[1 2 3]
  [4 6 7]]

 [[8 5 2]
  [0 7 3]]]
Original Array : 
 [[3 4 5]
 [2 9 0]]
Flattened Array : 
 [3 4 5 2 9 0]


In [6]:
arr=np.array([[-1,2,0,9],
              [4,-0.9,1,0],
              [2.5,0,7,8],
              [3,0,-5,5.0]])
temp1=arr[[0,1,2,3],[3,2,1,0]]
print("Elements with indices (0,3)(1,2)(2,1)(3,0):\n", temp1)
cond=arr>1
temp=arr[cond]
print("values greater than 1 : ", temp)


Elements with indices (0,3)(1,2)(2,1)(3,0):
 [9. 1. 0. 3.]
values greater than 1 :  [2.  9.  4.  2.5 7.  8.  3.  5. ]


# **Binary Operations**

In [7]:
a=np.array([1,5,6,8])
print("Adding 2 to each element :", a+2)
print("Subtract 3 from each element: ", a-3)
print("Multiply by 6:" , a*6)
print("Cubing each element : ", a**3)
b=np.array([[3,5,8],[9,0,7],[3,2,1]])
print("Original Array : \n",b)
print("Transpose of Array: \n",b.T)


Adding 2 to each element : [ 3  7  8 10]
Subtract 3 from each element:  [-2  2  3  5]
Multiply by 6: [ 6 30 36 48]
Cubing each element :  [  1 125 216 512]
Original Array : 
 [[3 5 8]
 [9 0 7]
 [3 2 1]]
Transpose of Array: 
 [[3 9 3]
 [5 0 2]
 [8 7 1]]


In [9]:
print("Largest Element in b: ", b.max())
print("Column Wise max Element : ", b.max(axis=0))
print("Row wise min element :", b.min(axis=1))
print("Cummulative sum along each row :\n", b.cumsum(axis=1))
print("Sum of array:\n", b.sum())

Largest Element in b:  9
Column Wise max Element :  [9 5 8]
Row wise min element : [3 0 1]
Cummulative sum along each row :
 [[ 3  8 16]
 [ 9  9 16]
 [ 3  5  6]]
Sum of array:
 38


In [10]:
a=np.array([[1,2],
            [5,0]])
b=np.array([[4,6],
            [1,2]])
print("sum of a and b:\n", a+b)
print("Multplication of a and b:\n", a*b)
print("Dot Product: \n", a.dot(b))

sum of a and b:
 [[5 8]
 [6 2]]
Multplication of a and b:
 [[ 4 12]
 [ 5  0]]
Dot Product: 
 [[ 6 10]
 [20 30]]


# **Sorting**

In [11]:
a=np.array([[7,0,2],
            [3,1,9],
            [-8,4,0]])
print("Sorted Array:\n", np.sort(a,axis=None))
print("Row Sorted Array:\n", np.sort(a,axis=1))
print("Column wise sort using mergesort :\n", np.sort(a,axis=0,kind="mergesort"))


Sorted Array:
 [-8  0  0  1  2  3  4  7  9]
Row Sorted Array:
 [[ 0  2  7]
 [ 1  3  9]
 [-8  0  4]]
Column wise sort using mergesort :
 [[-8  0  0]
 [ 3  1  2]
 [ 7  4  9]]


# **Stacking**

In [15]:
a=np.array([[1,2],
            [5,0]])
b=np.array([[4,6],
            [1,2]])
print("Horizontal stack : \n",np.hstack((a,b)))
print("Vertical Stack :\n", np.vstack((a,b)))
c=[5,6]
print("Column stacking: \n",np.column_stack((b,c)))
print("Concatenating to 2nd axis:\n",np.concatenate((a,b),1))


Horizontal stack : 
 [[1 2 4 6]
 [5 0 1 2]]
Vertical Stack :
 [[1 2]
 [5 0]
 [4 6]
 [1 2]]
Column stacking: 
 [[4 6 5]
 [1 2 6]]
Concatenating to 2nd axis:
 [[1 2 4 6]
 [5 0 1 2]]


# **Splitting**

In [20]:
a=np.array([[1,3,5,7,9],
            [2,4,6,8,10]])
print("Vertical Splitting: \n", np.vsplit(a,2))
print("Horizontal Splitting: ",np.hsplit(a,5))

Vertical Splitting: 
 [array([[1, 3, 5, 7, 9]]), array([[ 2,  4,  6,  8, 10]])]
Horizontal Splitting:  [array([[1],
       [2]]), array([[3],
       [4]]), array([[5],
       [6]]), array([[7],
       [8]]), array([[ 9],
       [10]])]
